#!/bin/bash
#############################################################################
#  Copyright (C) 2016
#  
#  Hamster is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Hamster is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Hamster.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-hadoop-helper
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-log
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-paths
source ${HAMSTER_SCRIPTS_HOME}/util/hamster-io

examples="share/hadoop/common/hadoop-common-3.0.0-alpha1-tests.jar"

sizes=( 1 4 8 16 )
clients=( 1 4 8 16 )
# index=( 0 1 2 3 4 )
index=( 1 ) 

for itt in {1..5}
do

for size in "${sizes[@]}"
do

size=`expr ${size} \* 1024`

Hamster_echo "*******************************************************"
Hamster_echo "* ECBench Encode ${size}MB"
Hamster_echo "*******************************************************"

for i in "${index[@]}"
do
for client in "${clients[@]}"
do
command="${hadoopcmdprefix}/yarn jar ${examples} org.apache.hadoop.io.erasurecode.rawcoder.RawErasureCoderBenchmark encode ${i} ${client} ${size} 1024"
echo "Running $command" >&2
$command
done
done

Hamster_echo "*******************************************************"
Hamster_echo "* ECBench Decode ${size}MB"
Hamster_echo "*******************************************************"

for i in "${index[@]}"
do
for client in "${clients[@]}"
do
command="${hadoopcmdprefix}/yarn jar ${examples} org.apache.hadoop.io.erasurecode.rawcoder.RawErasureCoderBenchmark decode ${i} ${client} ${size} 1024"
echo "Running $command" >&2
$command
done
done

done
done

exit 0
