#!/bin/bash
#############################################################################
#  Copyright (C) 2016
#  
#  Hamster is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Hamster is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Hamster.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This script is the core terasort running script.  For the most part,
# it shouldn't be edited.  See job submission files for configuration
# details.

source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-hadoop-helper
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-log
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-paths
source ${HAMSTER_SCRIPTS_HOME}/util/hamster-io

export PATH=$PATH:${HADOOP_HOME}/bin:${HIVE_HOME}/bin

job="tpch"
bench_home=${HAMSTER_SCRIPTS_HOME}/benchmarks/hive-testbench
gen_script=${bench_home}/${job}-setup.sh
run_script=${bench_home}/runSuite.pl
size=300
policy="erasurecode"

cd ${bench_home}

# directories used in this shell are made in another shell, so do NOT remove directories

if [ "${policy}X" == "erasurecodeX" ]
then
    Hamster_command "${hadoopcmdprefix}/hdfs erasurecode -setPolicy -p RS-DEFAULT-6-3-64k ${path_prefix}"
    Hamster_command "${hadoopcmdprefix}/hdfs erasurecode -getPolicy ${path_prefix}"
    sleep 30
fi


Hamster_echo "*******************************************************"
Hamster_echo "* Hive TPC ${job} ${size}GB"
Hamster_echo "*******************************************************"

Hamster_command "${gen_script} ${size}"

for i in {1..3}
do
    sleep 30

    Hamster_command "${run_script} ${job} ${size}"
done

exit 0
