#!/bin/bash
#############################################################################
#  Copyright (C) 2016
#  
#  Hamster is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Hamster is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Hamster.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-hadoop-helper
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-job-helper
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-log
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-paths
source ${HAMSTER_SCRIPTS_HOME}/util/hamster-io

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shi.876/workspace/bigdata/hadoop-${HADOOP_VERSION}/lib/native:/home/shi.876/lib
export CAFFE_ON_SPARK=${HOME}/caffe_tools/CaffeOnSpark
export SPARK_WORKER_INSTANCES=4
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CAFFE_ON_SPARK}/caffe-public/distribute/lib:${CAFFE_ON_SPARK}/caffe-distri/distribute/lib
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CUDA_HOME}/lib:${CUDA_HOME}/lib64:${MKL_HOME}/lib/intel64/

prefix="file:///scratch/shi.876/ImageNet"

Hamster_echo "*******************************************************"
Hamster_echo "* CaffeOnSpark BIN2SEQ"
Hamster_echo "*******************************************************"

# submit job
jobs=( "train" "val" )
for current in "${jobs[@]}"
do
    Hamster_spark_submit "--master yarn --deploy-mode cluster --num-executors ${SPARK_WORKER_INSTANCES} \
        --executor-memory 350g \
        --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
        --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
        --class com.yahoo.ml.caffe.tools.Binary2Sequence \
        ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
        -imageRoot ${prefix}/RawImages/${current}_20 -labelFile ${prefix}/RawImages/${current}_20/${current}.txt \
        -output ${prefix}/SequenceFile/${current}_20/ "
done

exit 0
