#!/bin/bash
#############################################################################
#  Copyright (C) 2016
#  
#  Hamster is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Hamster is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Hamster.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-hadoop-helper
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-job-helper
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-log
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-paths
source ${HAMSTER_SCRIPTS_HOME}/util/hamster-io

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shi.876/workspace/bigdata/hadoop-${HADOOP_VERSION}/lib/native:/home/shi.876/lib
export CAFFE_ON_SPARK=${HOME}/caffe_tools/CaffeOnSpark
export SPARK_HOME=${HOME}/workspace/bigdata/spark-1.6.3-bin-hadoop2.6
export SPARK_WORKER_INSTANCES=4
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CAFFE_ON_SPARK}/caffe-public/distribute/lib:${CAFFE_ON_SPARK}/caffe-distri/distribute/lib
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CUDA_HOME}/lib:${CUDA_HOME}/lib64:${MKL_HOME}/lib/intel64/

Hamster_echo "*******************************************************"
Hamster_echo "* CaffeOnSpark LMDB2DF"
Hamster_echo "*******************************************************"

base_dir=file:///scratch/shi.876/ImageNet/
hdfs_dir=/output

# submit job
jobs=( "ilsvrc12_train_lmdb" "ilsvrc12_val_lmdb" )
for current in "${jobs[@]}"
do
    Hamster_spark_submit "--master yarn --deploy-mode cluster --num-executors ${SPARK_WORKER_INSTANCES} \
        --executor-memory 300g \
        --conf spark.driver.extraLibraryPath="${LD_LIBRARY_PATH}" \
        --conf spark.executorEnv.LD_LIBRARY_PATH="${LD_LIBRARY_PATH}" \
        --class com.yahoo.ml.caffe.tools.LMDB2DataFrame \
        ${CAFFE_ON_SPARK}/caffe-grid/target/caffe-grid-0.1-SNAPSHOT-jar-with-dependencies.jar \
        -imageRoot ${base_dir}/LMDB/$current -outputFormat parquet -output ${hdfs_dir}/${current%_*} "

    Hamster_command "${HADOOP_HOME}/${hadoopcmdprefix}/hadoop fs -get ${hdfs_dir}/${current%_*} ${base_dir}/DataFrame/"
done

exit 0
