#!/bin/bash
#############################################################################
#  Copyright (C) 2016
#  
#  Hamster is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Hamster is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Hamster.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-hadoop-helper
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-log
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-paths
source ${HAMSTER_SCRIPTS_HOME}/util/hamster-io

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/shi.876/workspace/bigdata/hadoop-${HADOOP_VERSION}/lib/native:/home/shi.876/lib

testdfsioexamples="share/hadoop/mapreduce/hadoop-mapreduce-examples-*.jar"

dir=/benchmarks

for i in {1..3}
do
    opts="-D mapreduce.randomwriter.mapsperhost=4 -D mapreduce.randomwriter.bytespermap=67108864"

    command="${hadoopcmdprefix}/hadoop fs -rm -r -f -skipTrash ${dir}"
    echo "Running $command" >&2
    $command

    sleep 5

    Hamster_echo "*******************************************************"
    Hamster_echo "* RandomWrite"
    Hamster_echo "*******************************************************"

    Hamster_command "${hadoopcmdprefix}/yarn jar ${testdfsioexamples} randomwriter ${opts} ${dir}/rand_in"

    sleep 5

    Hamster_echo "*******************************************************"
    Hamster_echo "* Sort"
    Hamster_echo "*******************************************************"

    Hamster_command "${hadoopcmdprefix}/yarn jar ${testdfsioexamples} sort ${dir}/rand_in ${dir}/rand_out"

done

exit 0
