#!/bin/bash
#############################################################################
#  Copyright (C) 2016
#  
#  Hamster is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Hamster is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Hamster.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# This file has common run functions.  Should be sourced and used only
# in hamster-run* files.

source ${HAMSTER_SCRIPTS_HOME}/lib/exports/hamster-exports-submission-type
source ${HAMSTER_SCRIPTS_HOME}/lib/exports/hamster-exports-dirs
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-calculate-values
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-log
source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-helper
source ${HAMSTER_SCRIPTS_HOME}/util/hamster-io

__Hamster_job_time_minutes () {
    if [ "${HAMSTER_SUBMISSION_TYPE}" == "sbatchsrun" ]
    then
        local timeleftwalltime=`squeue -j ${SLURM_JOB_ID} -h -o %L`
        if [ "${timeleftwalltime}" == "NOT_SET" ] || [ "${timeleftwalltime}" == "UNLIMITED" ]
        then
            local walltimeminutes=`expr ${HAMSTER_TIMELIMIT_MINUTES} - ${hamster_startup_time_value}`
        else
            Hamster_walltime_to_minutes ${timeleftwalltime}
            local walltimeminutes=${hamster_walltimetominutes}
        fi
        __jobtimeminutes=`expr ${walltimeminutes} - ${hamster_shutdown_time_value}`
    else
        local timeleftminutes=`expr ${HAMSTER_TIMELIMIT_MINUTES} - ${hamster_startup_time_value}`
        __jobtimeminutes=`expr ${timeleftminutes} - ${hamster_shutdown_time_value}`
    fi
}

Hamster_job_time_seconds () {
    __Hamster_job_time_minutes
    hamster_jobtimeseconds=`expr ${__jobtimeminutes}  \* 60`
}

__Hamster_wait_script_signal_on_timeout () {
    local scriptpid=$1
    local timeoutminutes=$2
    local signalnumber=$3
    # We sleep in 30 second chunks, so times 2
    local scriptsleepiterations=`expr ${timeoutminutes}  \* 2`
    local scriptexitted=0

    for i in `seq 1 ${scriptsleepiterations}`
    do
        if kill -0 ${scriptpid} 2&> /dev/null
        then
            sleep 30
        else
            scriptexitted=1
            break
        fi
    done

    if [ "${scriptexitted}" == "0" ]
    then
        Hamster_echo "Killing script, did not exit within time limit"
        kill -s ${signalnumber} ${scriptpid}
        return 1
    fi

    return 0
}

Hamster_wait_script_kill_on_job_timeout () {
    local scriptpid=$1

    # Will set jobtimeminutes
    __Hamster_job_time_minutes

    __Hamster_wait_script_signal_on_timeout $scriptpid $__jobtimeminutes 9

    return $?
}

Hamster_wait_script_sigusr2_on_job_timeout () {
    local scriptpid=$1

    # Will set jobtimeminutes
    __Hamster_job_time_minutes

    __Hamster_wait_script_signal_on_timeout $scriptpid $__jobtimeminutes 12

    return $?
}

__Hamster_calculate_waittimes_count () {
    local hamsterstartuptimeseconds=`expr ${hamster_startup_time_value} \* 60`

    if [ "${hamster_run_total_sleep_wait}" -lt "${hamsterstartuptimeseconds}" ]
    then  
        # Could be more dynamic w/ slurm call to determine current
        # run time, but probably is sufficient for this trivial
        # part.  Minimally, have to leave the hamster_run_total_sleep_wait code
        # around for non-slurm systems.
        local waittimeseconds=`expr ${hamsterstartuptimeseconds} - ${hamster_run_total_sleep_wait}`

        if [ "${waittimeseconds}" -lt 30 ]
        then
            waittimeseconds=30
        fi
        
        __hamster_waittimes_count=`expr ${waittimeseconds} \/ 30`
    else
        __hamster_waittimes_count=1
    fi
}

Hamster_check_service_up () {
    local projectname=$1
    local callbackcheck=$2

    # Will set __hamster_waittimes_count
    __Hamster_calculate_waittimes_count
                
    for i in `seq 1 ${__hamster_waittimes_count}`
    do
        $callbackcheck
        
        if [ $? -eq 0 ]
        then
            return 0
        fi

        Hamster_echo "Waiting 30 more seconds for services to come up"
        sleep 30
        hamster_run_total_sleep_wait=`expr ${hamster_run_total_sleep_wait} + 30`
    done

    Hamster_echo "Part or all of ${projectname} service didn't come up, setup problem or maybe need to increase HAMSTER_STARTUP_TIME"
    return 1
}
