#!/bin/bash
#############################################################################
#  Copyright (C) 2016
#
#  Hamster is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  Hamster is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Hamster.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

if [ "${HADOOP_SETUP}" == "yes" ]
then
    version=$(Hamster_hadoop_version)
    if [ "$version" == "1" ]
    then
        hadoopsetupscriptprefix="bin"
        hadoopcmdprefix="bin"
        dfsadminscript="hadoop"
    elif [ "$version" == "2" ]
    then
        hadoopsetupscriptprefix="sbin"
        hadoopcmdprefix="bin"
        dfsadminscript="hdfs"
    elif [ "$version" == "3" ]
    then
        hadoopsetupscriptprefix="sbin"
        hadoopcmdprefix="bin"
        dfsadminscript="hdfs"
    fi
fi
if [ "${HIVE_SETUP}" == "yes" ]
then
    hivesetupscriptprefix="bin"
    zksetupscriptprefix="bin"
fi
