#!/bin/bash
#############################################################################
#  Copyright (C) 2016
#  
#  Hamster is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Hamster is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Hamster.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

# helper log functions.

__Hamster_output_internal_message () {
    local leveltype=$1
    shift
    local msg=$@

    echo "$(hostname)> Hamster Internal ${leveltype}: " $@
}

Hamster_output_internal_warning () {
    __Hamster_output_internal_message "Warning" $@
}

Hamster_output_internal_error () {
    __Hamster_output_internal_message "Error" $@
}
