#!/bin/bash
#############################################################################
#  Copyright (C) 2016
#  
#  Hamster is free software; you can redistribute it and/or modify it
#  under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  Hamster is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with Hamster.  If not, see <http://www.gnu.org/licenses/>.
#############################################################################

source ${HAMSTER_SCRIPTS_HOME}/lib/hamster-lib-defaults

if [ "${HAMSTER_STARTUP_TIME}X" != "X" ]
then
    hamster_startup_time_value=${HAMSTER_STARTUP_TIME}
else
    hamster_startup_time_value=${default_startup_time}
fi

if [ "${HAMSTER_SHUTDOWN_TIME}X" != "X" ]
then
    hamster_shutdown_time_value=${HAMSTER_SHUTDOWN_TIME}
else
    hamster_shutdown_time_value=${default_shutdown_time}
fi
